### ISSUE TITLE
"May 31" seems stuck as part of the "next 5 games" list

### ISSUE THREAD

**Issue by acwinter** [kyleconroy/vogeltron#12]
in the sidebar panel where the list of the next 5 games to be played is, the May 31 game against St. Louis seems stuck there -- and it should long ago have been replaced with an _actual_ upcoming game.

**Comment by kyleconroy** [comment]
Fixed

**Comment by acwinter** [comment]
Thank you Kyle

(Pls excuse any odd auto corrections.)
