### ISSUE TITLE
Bot stopped working 2013-07-16 07:55 PM PDT

### ISSUE THREAD

**Issue by acwinter** [kyleconroy/vogeltron#14]
just found out about this because (a) we were on All Star Break and (b) today's Gameday thread wasn't posted. (I logged in as SFGBot and posted it myself in hopes that if it is resurrected it can update the header info properly...)

thanks, man.

**Comment by kyleconroy** [comment]
God, so sorry I missed this message, things have been crazy. I'll get on a fix now.

**Comment by acwinter** [comment]
(I'll add to GitHub as well. have already PM'd /u/derferman)

D:

got admonished by the reddit admins for having text that's contra the reddit policy (didn't know that!). can you remove this text from the gameday and post game threads, please:

"Please upvote for attention; self.post, no karma" (post game thread)

"UPVOTE FOR VISIBILITY" (gameday thread)

thanks. and sending by email as well.

PNB

**Comment by kyleconroy** [comment]
Fixed the bot and removed the upvote text. The bot now stickies the gameday / postgame thread automatically.
