### ISSUE TITLE
text change (remove "upvote for visibility" from gameday / post game threads)

### ISSUE THREAD

**Issue by acwinter** [kyleconroy/vogeltron#15]
(already sent by email and have already PM'd /u/derferman)

D:

got admonished by the reddit admins for having text that's contra the reddit policy (didn't know that!). can you remove this text from the gameday and post game threads, please:

"Please upvote for attention; self.post, no karma" (post game thread)

"UPVOTE FOR VISIBILITY" (gameday thread)

thanks. and sending by email as well.

PNB

**Comment by kyleconroy** [comment]
Upvote text has been removed
