### ISSUE TITLE
Automatically post Gameday and Post-Game threads

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/vogeltron#2]
A sample [gameday thread](www.reddit.com/r/SFGiants/comments/1bqdzu/gameday_thread_4513_cardinals_westbrook_at_giants/) and [post-game thread](http://www.reddit.com/r/SFGiants/comments/1brktu/postgame_thread_45_giants_vs_cardinals_1_join_the/)

**Comment by zwgraham** [comment]
Should the mods manually update the thread during delays/schedule changes?

**Comment by kyleconroy** [comment]
The bot should be able to handle this on its own. The ESPN schedule will always know when the next game is, even when the schedule changes.

**Comment by kyleconroy** [comment]
The threads are now created.
